Update dired.py
Missing DiredBaseCommand as the parent for the DiredCommand. Or else on line 76 self.display_path(f) will cause an "AttributeError: 'DiredCommand' object has no attribute 'display_path'"